#!/bin/sh
tmux new-session -d -s main
tmux send-keys  -t main:0 'cd ~/ ; clear' C-m
tmux new-window -t main:1 '~/src/ranger/ranger.py'
tmux rename-window -t main:1 files 
tmux new-window -t main:2 alpine
tmux rename-window -t main:2 mail
tmux new-window -t main:3 'newsbeuter -r'
tmux rename-window -t main:3 news
tmux new-window -t main:4 'cmus'
tmux rename-window -t main:4 music
tmux new-window -t main:5 'wicd-curses'
tmux rename-window -t main:5 wifi
tmux select-window -t main:0
tmux att -t main
