#!/bin/sh

PID=`pgrep offlineimap`

###
# what to do if it's still running? uncomment
# only one of the options below:
###
#[ -n "$PID" ] && kill $PID     # kill it and resync now
[ -n "$PID" ] && exit 1         # exit and let it finish
###

offlineimap -o -u Noninteractive.Quiet &>/dev/null &
