colorscheme macvim " Use the macvim colourscheme
set autoindent
set smartindent
set confirm	" Show save dialog if command won't work with unsaved changes
set hidden	" Switch from unsaved buffer without saving, undo history for multiple files, warning on closing without saving
set history=1000	" Lots of history
set incsearch	" Search incrementally
set ignorecase	" Make search case insensitive...
set smartcase	" ... unless there's capital letters in the search
set laststatus=2	" Always display the status line
set statusline=%-(%F%m%r%h%w%)\ %{&ff}/%Y/%{&encoding}\ %=%(@\%03.3b\ %Ll\ %l,%v\ (%p%%)%) 
set mouse=a	" Enables the mouse in all modes, for scrolling and clicking on tabs (doesn't work in Terminal.app)
set number	" Show line numbers
set ruler	" Always show the cursor position
set showcmd	" Show commands on last line of screen
set nobackup	" Don't keep backups after closing
set writebackup	" Keep backups while open
set backupdir=~/.vim/backup " Keep backups in ~/.vim/backup
set directory=~/.vim/temp   " Keep temp files in ~/.vim/temp
set wildmenu	" Turn on the handy wildmenu
set wildignore+=*.DS_Store	" Ignore DS_Store files in wildmenu
set nomodeline	" Security fix
set tabpagemax=20	" Limit number of displayed tabs to 20 
set showtabline=2	" Always show tabs
set showmatch	" Show matching parentheses
set ffs=unix,mac 	" Support all filetypes, Mac first
set guifont=Monaco:h12 " Set the font for MacVim
set incsearch " incremental search
set hlsearch " highlight search terms
set visualbell t_vb=
if has("gui_running")
	set lines=60
	set columns=100
endif
syntax on	" Highlighting
filetype indent plugin on	" Detect filetype, indent according to filetype, switch on filetype plugins
imap jj <Esc>  " Exit insert mode with jj as well as the escape key (easier to reach)
map Y y$	" Make Y copy until the end of the line, instead of doing yy
map ,t :tabnew<CR>	" ,t to open a New tab
map ,n :tabnext<CR>	" ,n to cycle through open tabs
map ,jl :JekyllLink<CR> 
map ,jp :JekyllPost<CR> " ,jp to make a new post to mottr.am
map ,ji :JekyllPic<CR>  " ,ji to make a new image post to mottr.am
map ,jc :JekyllCommit<CR> " ,jc to commit changes to the mottr.am git repo
" Fuzzyfinder stuff
map ,f :FufFile<CR>
map ,b :FufBuffer<CR>
map <F2> :NERDTreeToggle<CR> " <F2> to toggle NERD Tree sidebar 
map <F3> :r !pbpaste<CR>	" <F3> to paste the Mac clipboard contents
map <F4> :setlocal spell spelllang=en_gb<CR>	" <F4> to turn on spellcheck
map <F5> :set nospell<CR>	" <F5> to turn off spellcheck
au BufWinLeave *.html,*.css mkview	" Saves folds in html and css
au BufWinEnter *.html,*.css silent loadview	" Opens html and css files with folds
au CursorHoldI * stopinsert	" Automatically leave insert mode after 'updatetime' ms - 4s by default - forces me to use vim properly! 
autocmd FileType html,xhtml,xml source ~/.vim/plugin/closetag.vim	" Close tags in HTML and XML files with http://www.vim.org/scripts/script.php?script_id=13
augroup mkd	" Markdown highlighting with http://plasticboy.com/markdown-vim-mode/
 autocmd BufRead *.markdown  set ai formatoptions=tcroqn2 comments=n:>
augroup END
let g:jekyll_path = "~/mottram" "For jekyll.vim
let delimitMate_autoclose = 1 " Automatically close tags and quotes with delimitMate plugin
let delimitMate = "(:),[:],{:},<:>" "The tags in question
let b:delimitMate_quotes = "\" ' ` *"
au FileType mail set tw=65

" Disable arrow keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>
