							" This is a very simple .vimrc file, but it suits me fine!
set confirm						" show save dialog if command won't work with unsaved changes
set hidden						" switch from unsaved buffer without saving, undo history for multiple files, warning on closing without saving
set laststatus=2					" always display the status line
set mouse=a						" enables the mouse in all modes, for scrolling and clicking on tabs
set nocompatible					" makes sure all new features are enabled
set number						" show line numbers
set showcmd						" show commands on last line of screen
syntax on						" highlighting
filetype indent plugin on				" auto-indenting based on filetype
:imap jj <Esc>						" exit insert mode with jj instead of the escape key
map Y y$						" makes Y copy until the end of the line, instead of doing yy
map <F2> :bnext<CR>					" F2 to cycle through open buffers
map <F3> :r !pbpaste<CR>				" F3 to paste the Mac clipboard contents
map <F4> :setlocal spell spelllang=en_gb<CR>		" Turn on spellcheck
map <F5> :set nospell<CR>				" Turn off spellcheck
au BufWinLeave *.html,*.css mkview			" saves folds in html and css
au BufWinEnter *.html,*.css silent loadview		" ditto
augroup mkd						" Markdown highlighting with http://plasticboy.com/markdown-vim-mode/
 autocmd BufRead *.markdown  set ai formatoptions=tcroqn2 comments=n:>
augroup END
