#! /bin/sh

bspc monitor -d 1 2 3 4

bspc config border_width        1
bspc config window_gap          6
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config top_padding         14

bspc config normal_border_color "#002b36"
bspc config focused_border_color "#657b83"
bspc config presel_border_color "#aada2c"
# bspc config normal_frame_opacity 0.0
# bspc config focused_frame_opacity 0.05


bspc config rule_command "$(which rule_command)"
bspwm_rules
