#!/bin/bash
cd ~/mottram
rm -rf ~/mottram/_site/*
ejekyll
mv ~/mottram/_site/htaccess.txt ~/mottram/_site/.htaccess
rsync -avz --delete --exclude='*.textdrive' _site/ mottram@chestnut.joyent.us:domains/mottr.am/web/public
