#!/bin/bash
cd ~/mottram
rm -rf ~/mottram/_site/*
ejekyll
mv ~/mottram/_site/htaccess.txt ~/mottram/_site/.htaccess
rsync -avz --delete --exclude='*.textdrive' _site/ mottram@chestnut.joyent.us:domains/mottr.am/web/public
curl -s "http://pingomatic.com/ping/?title=Mottr.am&blogurl=http%3A%2F%2Fmottr.am&rssurl=http%3A%2F%2Fmottr.am%2Fatom.xml&chk_weblogscom=on&chk_blogs=on&chk_feedburner=on&chk_syndic8=on&chk_newsgator=on&chk_myyahoo=on&chk_pubsubcom=on&chk_blogdigger=on&chk_blogstreet=on&chk_weblogalot=on&chk_icerocket=on&chk_newsisfree=on&chk_topicexchange=on&chk_google=on&chk_tailrank=on&chk_postrank=on&chk_skygrid=on&chk_collecta=on&chk_superfeedr=on" > /dev/null
