#!/bin/sh
# Wallpaper
#find ~/.wallpaper -type f -name "*.jpg" -print0 | shuf -n1 -z | xargs -0 imlibsetroot -s f
imlibsetroot -s f .wallpaper/misty-danube.jpg
# Keyboard & Trackpad
setxkbmap gb
xmodmap ~/.config/X/Xmodmap
xmodmap -e "pointer = 1 2 3 5 4"
unclutter &
# Clipboard
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
clipbored
# Load fonts
xset +fp /usr/share/fonts/local
xset fp rehash
# Notifications with dunst
dunst -key space -mod ctrl -to 4 -fn -*-terminus-*-r-normal-*-*-120-*-*-*-*-iso8859-* -geometry x2+1+1 -nb "#657b83" -nf "#002b36" &
# Conky status bar
conky | while read -r; do xsetroot -name "$REPLY"; done &
# Start dwm
exec dwm-start
