while true; do
	xsetroot -name "$( date +"%F %R" )"
	sleep 1m
done &
urxvtd &
feh --bg-scale ~/pics/misty-danube.jpg
dropboxd &
autocutsel -f
conky &>/dev/null &
setxkbmap gb
xfce4-clipman &
exec dwm
