#!/bin/sh
# Wallpaper
imlibsetroot -s f .wallpaper/misty-danube.jpg
# Keyboard & Trackpad
setxkbmap gb
xmodmap ~/.config/X/Xmodmap
xmodmap -e "pointer = 1 2 3 5 4"
unclutter -idle 2 &
# Clipboard
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
#clipbored
# Load fonts
xset +fp /usr/share/fonts/local
xset fp rehash
# Turn off screen after 5 minutes
xset +dpms
xset dpms 0 0 300
# Notifications with dunst
dunst -config /home/jack/.config/dunst/dunstrc &
# Compositing with compton
compton --config ~/.config/compton/compton.conf &
# Source .xprofile, loliclip
[ -f ~/.xprofile ] && . ~/.xprofile
# Status bar
while true; do
    xsetroot -name "£ $(netcfg current) $(awk 'END{print $4}' /proc/net/wireless | tr -d [:punct:])% ò $(acpi -b | awk 'sub(/,/,"") {print $4}' | tr -d [:punct:])% É $( date +"%A %d %B %R" ) "
   sleep 1m    # Update time every minute
done &
exec dwm-start

# Conky status bar
#conky | while read -r; do xsetroot -name "$REPLY"; done &
