#!/bin/sh
# bspwm settings
export XDG_CONFIG_HOME="$HOME/.config"
export BSPWM_SOCKET="/tmp/bspwm-socket"
export BSPWM_TREE="/tmp/bspwm.tree"
export BSPWM_TREE="/tmp/bspwm.history"
export BSPWM_TREE="/tmp/bspwm.stack"
export PATH=$PATH:/home/jack/.config/bspwm/bin

# panel settings
export PANEL_FONT="-*-termsyn.icons-medium-r-*-*-12-*-*-*-*-*-*-*"
export PANEL_FOREGROUND="#a89984"
export PANEL_BACKGROUND="#1d2021"
export PANEL_HEIGHT="14"

# source .xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

# wallpaper
hsetroot -solid "#282828"

# gb keyboard layout
setxkbmap gb

# Caps Lock = Escape
xmodmap ~/.config/X/Xmodmap

# os x-style scrolling
xmodmap -e "pointer = 1 2 3 5 4"

# set cursor
xsetroot -cursor_name left_ptr &

# load fonts
xset +fp /usr/share/fonts/local
xset fp rehash

# turn off screen after 5 minutes
xset +dpms
xset dpms 0 0 300

# synchronise clipboards and start clipmenu
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
clipmenud &

# start gpg-agent
eval $(gpg-agent --daemon) &

# start bspwm
exec bspwm
