#!/bin/sh
# privoxy, polipo
export http_proxy=http://localhost:8118

# keyboard shortcuts
sxhkd &

# notifications with dunst
dunst -config ~/.config/dunst/dunstrc &

# hide cursor after 2 seconds
unclutter -idle 2 &
