# File: ~/.zshrc
# Version: 0.3
# Author: Jack Mottram <j@ck.mottr.am>
# TODO: tidy up aliases & functions, use checks.
# TODO: sort out completion - bit iffy at the moment.
# TODO: move path & exports?
PATH="/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH"
export ZSH_DIR=$HOME/dotfiles/zsh
export ZSH_PLUGINS_DIR=$ZSH_DIR/plugins
source $ZSH_DIR/checks.zsh
source $ZSH_DIR/functions.zsh
source $ZSH_DIR/aliases.zsh
source $ZSH_DIR/history.zsh
source $ZSH_DIR/bindkeys.zsh
source $ZSH_DIR/applications.zsh
source $ZSH_DIR/completions.zsh
source $ZSH_DIR/plugins.zsh
source $ZSH_DIR/prompt.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
