# File: ~/.zshrc
# Version: 0.3
# Author: Jack Mottram <j@ck.mottr.am>
# TODO: exports.zsh
# TODO: tidy up aliases & functions, use checks
# General
PATH="/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH"
if [[ $IS_OSX -eq 1 ]]; then
    export EDITOR=/usr/local/bin/vim
elif [[ $IS_LINUX -eq 1 ]]; then
    export EDITOR=vim
fi

# Source checks, aliases, functions, plugins & prompt
export ZSH_DIR=$HOME/dotfiles/zsh
source $ZSH_DIR/checks.zsh
source $ZSH_DIR/functions.zsh
source $ZSH_DIR/aliases.zsh
source $ZSH_DIR/history.zsh
source $ZSH_DIR/bindkeys.zsh
source $ZSH_DIR/applications.zsh
source $ZSH_DIR/completions.zsh
fpath=($ZSH_DIR/zsh-completions/src $fpath)
fpath=(/usr/local/share/zsh/site-functions $fpath)
source $ZSH_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
source $ZSH_DIR/zsh-history-substring-search/zsh-history-substring-search.zsh
source $ZSH_DIR/opp/opp.zsh
source $ZSH_DIR/opp/opp/*.zsh
source $ZSH_DIR/prompt.zsh

